# Generated by Django 5.1.5 on 2025-01-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssms_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
