# Generated by Django 5.1.5 on 2025-01-23 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssms_model', '0002_alter_card_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('work_unit', models.CharField(max_length=200)),
                ('job_position', models.CharField(max_length=200)),
                ('id_number', models.CharField(max_length=200)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssms_model.gender')),
            ],
        ),
    ]
